name: devel

on:
  pull_request:
  push:
    branches:
      - master
    paths:
    - .github/workflows/devel.yml
    - go.mod
    - go.sum
    - '**.go'

jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.23.x
          - 1.24.x
          - 1.25.x
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-14
          - windows-2022
          - windows-11-arm
    runs-on: ${{ matrix.os}}
    steps:
      - name: Install
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: format
        run: |
          go fmt ./...
      - name: Vet
        run: |
          go vet ./...
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
          cache-key: ${{ matrix.go }}
      - name: Tests
        run: |
          go test ./... -v -timeout 30s -coverprofile=coverage.txt -covermode=atomic
      - name: Coverage
        uses: codecov/codecov-action@v5
        with:
          flags: unittests
          verbose: true
          name: codecov-cline
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        shell: bash
        run: |
          now=$(date -u '+%Y-%m-%dT%H:%m:%S')
          go build -v \
            -ldflags "-s -w \
            -X 'main.versionNumber=0.0.0' \
            -X 'main.buildTime=${now}' \
            -X 'main.buildCommit=${GITHUB_SHA}'" \
            -a -o bin/cline ./examples
          bin/cline --version
          bin/cline --help
      - name: Environment
        id: vars
        shell: bash
        run: |
          echo "Using go at: $(which go)"
          echo "Go version: $(go version)"
          echo "  Go environment:"
          go env
          echo "  System environment:"
          env
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "go_cache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.vars.outputs.go_cache }}
          key: ${{ runner.os }}-${{ matrix.go }}-go-ci-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go }}-go-ci
